// <auto-generated />
using System;
using BAD.Storage.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BAD.Storage.Migrations
{
    [DbContext(typeof(BadDbContext))]
    [Migration("20260518222402_AddApiCatalogOpenApiImport")]
    partial class AddApiCatalogOpenApiImport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.27");

            modelBuilder.Entity("BAD.Storage.Entities.ApiCatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoTitle")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("InfoVersion")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenApiVersion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("OperationsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SpecJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("ApiCatalogs");
                });

            modelBuilder.Entity("BAD.Storage.Entities.ExecutionFlow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DefinitionVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("ExecutionFlows");
                });

            modelBuilder.Entity("BAD.Storage.Entities.FlowRun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<int>("ExecutionFlowId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalMs")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MutatePerIteration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RequestCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutionFlowId");

                    b.HasIndex("StartedAt");

                    b.ToTable("FlowRuns");
                });

            modelBuilder.Entity("BAD.Storage.Entities.FlowRunStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientNodeId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Error")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FlowRunId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int?>("TestExecutionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TestExecutionId");

                    b.HasIndex("FlowRunId", "ClientNodeId");

                    b.ToTable("FlowRunSteps");
                });

            modelBuilder.Entity("BAD.Storage.Entities.GeneratorSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FieldConfigurations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("JsonTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JsonTemplateId", "Name")
                        .IsUnique();

                    b.ToTable("GeneratorSettings");
                });

            modelBuilder.Entity("BAD.Storage.Entities.JsonTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApiCatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenApiOperationKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.HasIndex("ApiCatalogId", "OpenApiOperationKey")
                        .IsUnique()
                        .HasFilter("[ApiCatalogId] IS NOT NULL AND [OpenApiOperationKey] IS NOT NULL");

                    b.ToTable("JsonTemplates");
                });

            modelBuilder.Entity("BAD.Storage.Entities.RequestConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ApiCatalogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("AuthValue")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Headers")
                        .HasColumnType("TEXT");

                    b.Property<int?>("JsonTemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("OpenApiOperationKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JsonTemplateId");

                    b.HasIndex("ApiCatalogId", "OpenApiOperationKey")
                        .IsUnique()
                        .HasFilter("[ApiCatalogId] IS NOT NULL AND [OpenApiOperationKey] IS NOT NULL");

                    b.ToTable("RequestConfigs");
                });

            modelBuilder.Entity("BAD.Storage.Entities.TestExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("AvgResponseTimeMs")
                        .HasColumnType("REAL");

                    b.Property<string>("BaseJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("BodyMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("none");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExecutionMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("sequential");

                    b.Property<int>("FailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntervalMs")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MaxResponseTimeMs")
                        .HasColumnType("REAL");

                    b.Property<double>("MinResponseTimeMs")
                        .HasColumnType("REAL");

                    b.Property<bool>("MutatePerIteration")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MutationsConfig")
                        .HasColumnType("TEXT");

                    b.Property<string>("PresetUsed")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("RequestConfigId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("pending");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalRequests")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("RequestConfigId");

                    b.HasIndex("Status");

                    b.HasIndex("TemplateId");

                    b.ToTable("TestExecutions");
                });

            modelBuilder.Entity("BAD.Storage.Entities.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("DurationMs")
                        .HasColumnType("REAL");

                    b.Property<string>("Error")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Index")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestHeaders")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPayload")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseHeaders")
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TestExecutionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("TestExecutionId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("BAD.Storage.Entities.FlowRun", b =>
                {
                    b.HasOne("BAD.Storage.Entities.ExecutionFlow", "ExecutionFlow")
                        .WithMany("FlowRuns")
                        .HasForeignKey("ExecutionFlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ExecutionFlow");
                });

            modelBuilder.Entity("BAD.Storage.Entities.FlowRunStep", b =>
                {
                    b.HasOne("BAD.Storage.Entities.FlowRun", "FlowRun")
                        .WithMany("Steps")
                        .HasForeignKey("FlowRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BAD.Storage.Entities.TestExecution", "TestExecution")
                        .WithMany()
                        .HasForeignKey("TestExecutionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("FlowRun");

                    b.Navigation("TestExecution");
                });

            modelBuilder.Entity("BAD.Storage.Entities.GeneratorSetting", b =>
                {
                    b.HasOne("BAD.Storage.Entities.JsonTemplate", "JsonTemplate")
                        .WithMany("GeneratorSettings")
                        .HasForeignKey("JsonTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JsonTemplate");
                });

            modelBuilder.Entity("BAD.Storage.Entities.JsonTemplate", b =>
                {
                    b.HasOne("BAD.Storage.Entities.ApiCatalog", "ApiCatalog")
                        .WithMany()
                        .HasForeignKey("ApiCatalogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApiCatalog");
                });

            modelBuilder.Entity("BAD.Storage.Entities.RequestConfig", b =>
                {
                    b.HasOne("BAD.Storage.Entities.ApiCatalog", "ApiCatalog")
                        .WithMany()
                        .HasForeignKey("ApiCatalogId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BAD.Storage.Entities.JsonTemplate", "JsonTemplate")
                        .WithMany("RequestConfigs")
                        .HasForeignKey("JsonTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApiCatalog");

                    b.Navigation("JsonTemplate");
                });

            modelBuilder.Entity("BAD.Storage.Entities.TestExecution", b =>
                {
                    b.HasOne("BAD.Storage.Entities.RequestConfig", "RequestConfig")
                        .WithMany("TestExecutions")
                        .HasForeignKey("RequestConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BAD.Storage.Entities.JsonTemplate", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("RequestConfig");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("BAD.Storage.Entities.TestResult", b =>
                {
                    b.HasOne("BAD.Storage.Entities.TestExecution", "TestExecution")
                        .WithMany("Results")
                        .HasForeignKey("TestExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestExecution");
                });

            modelBuilder.Entity("BAD.Storage.Entities.ExecutionFlow", b =>
                {
                    b.Navigation("FlowRuns");
                });

            modelBuilder.Entity("BAD.Storage.Entities.FlowRun", b =>
                {
                    b.Navigation("Steps");
                });

            modelBuilder.Entity("BAD.Storage.Entities.JsonTemplate", b =>
                {
                    b.Navigation("GeneratorSettings");

                    b.Navigation("RequestConfigs");
                });

            modelBuilder.Entity("BAD.Storage.Entities.RequestConfig", b =>
                {
                    b.Navigation("TestExecutions");
                });

            modelBuilder.Entity("BAD.Storage.Entities.TestExecution", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
