// <auto-generated />
using System;
using BAD.Storage.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BAD.Storage.Migrations
{
    [DbContext(typeof(BadDbContext))]
    partial class BadDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BAD.Storage.Entities.GeneratorSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FieldConfigurations")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("JsonTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("JsonTemplateId");

                    b.ToTable("GeneratorSettings");
                });

            modelBuilder.Entity("BAD.Storage.Entities.JsonTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("JsonTemplates");
                });

            modelBuilder.Entity("BAD.Storage.Entities.RequestConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("AuthValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("JsonTemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.HasKey("Id");

                    b.HasIndex("JsonTemplateId");

                    b.ToTable("RequestConfigs");
                });

            modelBuilder.Entity("BAD.Storage.Entities.TestExecution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("AvgResponseTimeMs")
                        .HasColumnType("float");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FailureCount")
                        .HasColumnType("int");

                    b.Property<double>("MaxResponseTimeMs")
                        .HasColumnType("float");

                    b.Property<double>("MinResponseTimeMs")
                        .HasColumnType("float");

                    b.Property<string>("PresetUsed")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("RequestConfigId")
                        .HasColumnType("int");

                    b.Property<int>("SuccessCount")
                        .HasColumnType("int");

                    b.Property<int>("TotalRequests")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt");

                    b.HasIndex("RequestConfigId");

                    b.ToTable("TestExecutions");
                });

            modelBuilder.Entity("BAD.Storage.Entities.TestResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("DurationMs")
                        .HasColumnType("float");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("bit");

                    b.Property<string>("RequestPayload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<int>("TestExecutionId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TestExecutionId");

                    b.ToTable("TestResults");
                });

            modelBuilder.Entity("BAD.Storage.Entities.GeneratorSetting", b =>
                {
                    b.HasOne("BAD.Storage.Entities.JsonTemplate", "JsonTemplate")
                        .WithMany("GeneratorSettings")
                        .HasForeignKey("JsonTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JsonTemplate");
                });

            modelBuilder.Entity("BAD.Storage.Entities.RequestConfig", b =>
                {
                    b.HasOne("BAD.Storage.Entities.JsonTemplate", "JsonTemplate")
                        .WithMany("RequestConfigs")
                        .HasForeignKey("JsonTemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("JsonTemplate");
                });

            modelBuilder.Entity("BAD.Storage.Entities.TestExecution", b =>
                {
                    b.HasOne("BAD.Storage.Entities.RequestConfig", "RequestConfig")
                        .WithMany("TestExecutions")
                        .HasForeignKey("RequestConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestConfig");
                });

            modelBuilder.Entity("BAD.Storage.Entities.TestResult", b =>
                {
                    b.HasOne("BAD.Storage.Entities.TestExecution", "TestExecution")
                        .WithMany("Results")
                        .HasForeignKey("TestExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TestExecution");
                });

            modelBuilder.Entity("BAD.Storage.Entities.JsonTemplate", b =>
                {
                    b.Navigation("GeneratorSettings");

                    b.Navigation("RequestConfigs");
                });

            modelBuilder.Entity("BAD.Storage.Entities.RequestConfig", b =>
                {
                    b.Navigation("TestExecutions");
                });

            modelBuilder.Entity("BAD.Storage.Entities.TestExecution", b =>
                {
                    b.Navigation("Results");
                });
#pragma warning restore 612, 618
        }
    }
}
